Repository canonical/pgbouncer-k8s-operator, pull requests merged in 2025-04, with the labels that each got.

#568 Create SECURITY.md
  SECURITY.md
Labels: not bug or enhancement

#572 [DPE-6218] Static code analysis
  .github/workflows/tiobe_scan.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#313 [DPE-6903] Move user list to shared memory
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/pgbouncer_k8s/v0/pgb.py
  src/charm.py
  src/constants.py
  src/relations/backend_database.py
  src/relations/db.py
  src/relations/peers.py
  src/relations/pgbouncer_provider.py
  src/upgrade.py
  templates/pgb_config.j2
  tests/integration/helpers/helpers.py
  tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
  tests/integration/relations/test_backend_database.py
  tests/integration/relations/test_db.py
  tests/integration/relations/test_db_admin.py
  tests/integration/relations/test_peers.py
  tests/integration/test_tls.py
  tests/integration/test_trust.py
  tests/integration/test_upgrade.py
  tests/integration/test_upgrade_data_integrator.py
  tests/integration/test_upgrade_from_stable.py
  tests/unit/relations/test_backend_database.py
  tests/unit/relations/test_db.py
  tests/unit/relations/test_peers.py
  tests/unit/relations/test_pgbouncer_provider.py
  tests/unit/test_charm.py
  tests/unit/test_pgb.py
  tests/unit/test_upgrade.py
Labels: enhancement, Libraries: Out of sync
