Repository canonical/pgbouncer-k8s-operator, pull requests merged in 2025-02, with the labels that each got.

#517 [MISC] Update libs
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/data_platform_libs/v0/data_models.py
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  lib/charms/tempo_coordinator_k8s/v0/tracing.py
Labels: Libraries: OK

#495 [DPE-6209] Add support for expose-external config to configure external connectivity
  .github/workflows/ci.yaml
  config.yaml
  poetry.lock
  src/charm.py
  src/config.py
  src/constants.py
  src/relations/db.py
  src/relations/pgbouncer_provider.py
  src/upgrade.py
  tests/integration/helpers/helpers.py
  tests/integration/juju_.py
  tests/integration/relations/pgbouncer_provider/helpers.py
  tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
  tests/integration/relations/test_backend_database.py
  tests/integration/relations/test_db.py
  tests/integration/relations/test_db_admin.py
  tests/integration/relations/test_peers.py
  tests/integration/test_expose_external.py
  tests/integration/test_node_port.py
  tests/integration/test_trust.py
  tests/integration/test_upgrade_data_integrator.py
  tests/unit/conftest.py
  tests/unit/relations/test_db.py
  tests/unit/relations/test_pgbouncer_provider.py
  tests/unit/test_charm.py
  tests/unit/test_upgrade.py
Labels: Libraries: Out of sync

#520 Fix minor typo in access of ServiceSpec object
  src/charm.py
  tests/integration/test_expose_external.py
Labels: Libraries: OK

#535 [MISC] Enable RBAC in tests
  concierge.yaml
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  tests/integration/test_config.py
  tests/integration/test_trust.py
Labels: Libraries: OK, not bug or enhancement

#543 [MISC] Await config change
  tests/integration/test_upgrade_data_integrator.py
Labels: Libraries: OK, not bug or enhancement
